version: '3.8'
services:
    db:
        container_name: db
        build:
            context: '.'
            dockerfile: 'apps/notes/db/Dockerfile'
        ports:
            - '5432:5432'
        networks:
            - notes
    prisma:
        container_name: prisma
        depends_on:
            - db
        tty: true
        build:
            context: '.'
            dockerfile: apps/notes/prisma/Dockerfile
        volumes:
            - 'apps/notes/prisma/schema.prisma:/app/apps/notes/prisma/schema.prisma'
            - 'apps/notes/prisma/seed.ts:/app/apps/notes/prisma/seed.ts'
            - 'apps/notes/prisma/setup.sh:/app/apps/notes/prisma/setup.sh'
        networks:
            - notes
    server:
        container_name: server
        depends_on:
            prisma:
                condition: service_completed_successfully
        build:
            context: '.'
            dockerfile: apps/notes/server/docker/production/Dockerfile
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?connect_timeout=10
        ports:
            - '3000:3000'
        networks:
            - notes
    client:
        container_name: client
        depends_on:
            - server
        build:
            context: '.'
            dockerfile: apps/notes/client/docker/production/Dockerfile
        ports:
            - '4200:4200'
        networks:
            - notes

networks:
    notes:
        driver: bridge
