version: '3.3'
name: notes
services:
    client:
        depends_on: ['server']
        container_name: client
        build:
            context: '../../../'
            dockerfile: apps/notes/client/docker/Dockerfile.production
        ports:
            - '4200:4200'
        networks:
            - notes
    server:
        container_name: server
        build:
            context: '../../../'
            dockerfile: apps/notes/server/docker/Dockerfile.production
        ports:
            - '3000:3000'
        networks:
            - notes

networks:
    notes:
        driver: bridge
