version: '3.8'
name: notes
services:
    postgres:
        container_name: postgres
        build:
            context: '../../../'
            dockerfile: 'apps/notes/docker/db.Dockerfile'
        ports:
            - '5432:5432'
        networks:
            - notes
    prisma:
        container_name: prisma
        depends_on:
            - postgres
        build:
            context: '../../../'
            dockerfile: apps/notes/docker/prisma.Dockerfile
        networks:
            - notes
    server:
        container_name: server
        depends_on:
            prisma:
                condition: service_completed_successfully
        build:
            context: '../../../'
            dockerfile: apps/notes/server/docker/Dockerfile.production
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?connect_timeout=10
        ports:
            - '3000:3000'
        networks:
            - notes
    client:
        container_name: client
        depends_on:
            - server
        build:
            context: '../../../'
            dockerfile: apps/notes/client/docker/Dockerfile.production
        ports:
            - '4200:4200'
        networks:
            - notes

networks:
    notes:
        driver: bridge
