name: Docker Python

on:
    push:
        branches:
            - main

jobs:
    docker-python:
        permissions:
            contents: read
            actions: read
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Login to Github Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Derive SHAs
              uses: nrwl/nx-set-shas@v3

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Cache Node
              id: node_cache
              uses: actions/cache@v3
              with:
                  path: |
                      node_modules/
                  key: ubuntu-latest-node-${{ hashFiles('yarn.lock') }}
                  restore-keys: ubuntu-latest-node-

            - name: Install Node Dependencies
              if: steps.node_cache.outputs.cache-hit != 'true'
              run: yarn install --immutable

            - name: Build and Push Docker Image
              run: npx nx build docker-python
